<?php

namespace Anaxago\CoreBundle\Repository;

/**
 * InvestmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvestmentRepository extends \Doctrine\ORM\EntityRepository
{
}
